[tool.poetry]
name = "holmes"
version = "0.1.0"
description = ""
authors = ["albertoecf"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
langchain = "^0.0.350"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
